site_name: World Series of Warzone Dads (WSOWD)
site_url: https://www.wztourney.com
site_description: Warzone Tourney
site_author: wztourney

# repo_url: https://github.com/wztourney/wztourney.github.io

markdown_extensions:
  - tables

theme:
  name: 'material'
  palette:
    scheme: 'slate'
  # language: 'en'
  # features:
  #   - search.simple

